project:
  type: website
  render:
    - cv/*.qmd
    - index.qmd
    - research/*.qmd
    - teaching/*.qmd
    - blog/index.qmd
    - blog/**/*.qmd
  output-dir: _site

execute:
  freeze: auto

website:
  title: "Esteban Degetau"
  site-url: https://www.estebandegetau.com/
  description: "Esteban Degetau's Personal Website"
  repo-url: https://github.com/estebandegetau/estebandegetau.github.io
  google-analytics: "G-11D42BZNRY"
  navbar:
    left:
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
      - href: blog/index.qmd
        text: Blog
      - href: cv/index.qmd
        text: CV
    right:
      - icon: rss
        href: index.xml

  page-footer: 
    left: "c. Esteban Degetau, 2026" 
    right: 
      - icon: github
        href: https://github.com/estebandegetau
      - icon: twitter 
        href: https://x.com/estebandegetau



format: 
  html:
    title-block-banner: true
    css: styles.css
    tbl-colwidths: [80,20]


# brand: _brand.yml
