---
title: "Curriculum vitae"
subtitle: "[estebandegetau@gmail.com](mailto:estebandegetau@gmail.com)"
date-modified: "`r Sys.Date()`"
format: 
  html: 
      css: styles.css
tbl-colwidths: [70,30]
author: 
  - name: "Esteban Degetau Sentíes"
    orcid: 0009-0004-4095-8819
    email: estebandegetau@gmail.com
    url: estebandegetau.com
    github: estebandegetau
    phone: +52 5613810985
---

```{r}
#| include: false

pacman::p_load(markdown)

```

## Education

+:---------------------------------------------------------------------------------------------------------------------------------------------------+-------------------:+
| **MA in Applied Economics**                                                                                                                        | Since Fall 2023    |
|                                                                                                                                                    |                    |
| Instituto Tecnológico Autónomo de México ([ITAM](https://www.itam.mx/en))                                                                          | Part-time schedule |
+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| **MicroMasters in Data, Economics and Development Policy**                                                                                         | 2022               |
|                                                                                                                                                    |                    |
| Massachusetts Institute of Technology ([MITx](https://mitxonline.mit.edu/certificate/program/cc5f08c4-e64b-4f5b-ac83-2fc1868b1c9a/ "Certificate")) |                    |
+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| **BS in Economics**                                                                                                                                | 2016 - 2021        |
|                                                                                                                                                    |                    |
| Instituto Tecnológico Autónomo de México ([ITAM](https://www.itam.mx/en))                                                                          |                    |
+----------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+

## Work experience

+:---------------------------------------------------------------------+-------------:+
| **Fiscal policy planning manager**                                   | Since 2023   |
|                                                                      |              |
| Planning and Evaluation Unit                                         |              |
|                                                                      |              |
| Collection and Incorporation Directorate                             |              |
|                                                                      |              |
| Mexico's Social Security Institute ([IMSS](https://www.gob.mx/imss)) |              |
+----------------------------------------------------------------------+--------------+
| **Business analyst**                                                 | 2019 - 2021  |
|                                                                      |              |
| at [CEROMULTAS](https://ceromultas.mx/)                              |              |
+----------------------------------------------------------------------+--------------+
| **International trade analyst**                                      | 2018         |
|                                                                      |              |
| at [T-Rez Consulting](https://www.t-rezconsulting.com/)              |              |
+----------------------------------------------------------------------+--------------+

## Research experience

+:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------:+
| **Data and field Research assistant**                                                                                                                                      | 2022 - 2023 |
|                                                                                                                                                                            |             |
| to [Enrique Seira](http://econ.msu.edu/faculty/seira/index.php) and [Joyce Sadka](https://faculty.itam.mx/facultad/4943-joyce-carol-sadka)                                 |             |
|                                                                                                                                                                            |             |
| at the [Improving Labor Courts](https://www.povertyactionlab.org/initiative-project/improving-labor-courts-fighting-corruption-competition), a J-PAL Governance Initiative |             |
|                                                                                                                                                                            |             |
| Center for Economic Research ([CIE](http://cie.itam.mx/))                                                                                                                  |             |
|                                                                                                                                                                            |             |
| Instituto Tecnológico Autónomo de México ([ITAM](https://www.itam.mx/en))                                                                                                  |             |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+

## Teaching experience

+:--------------------------------------------------------------------------+-------------------------:+
| **Teaching assistant**                                                    | Fall 2022 to Spring 2023 |
|                                                                           |                          |
| to [Joyce Sadka](https://faculty.itam.mx/facultad/4943-joyce-carol-sadka) |                          |
|                                                                           |                          |
| Economic Analysis of Law (Undergrad)                                      |                          |
|                                                                           |                          |
| Instituto Tecnológico Autónomo de México ([ITAM](https://www.itam.mx/en)) |                          |
+---------------------------------------------------------------------------+--------------------------+

## Recognitions

+:-------------------------------------------------------------------------------------------------------+----------:+
| **Honorable mention**                                                                                  | 2021      |
|                                                                                                        |           |
| Undergraduate [COFECE Essay contest](https://www.cofece.mx/revista-del-premio-cofece-de-ensayo-2021/). |           |
+--------------------------------------------------------------------------------------------------------+-----------+