

```{r}
d <- Sys.Date()
```


|  |  |
|:-----------------|:----------|
| **Barcelona School of Economics**                      | [estebandegetau\@gmail.com](mailto:estebandegetau@gmail.com) |
| Ramón Trias Fargas, 25-27, 08005 | [www.estebandegetau.com](https://www.estebandegetau.com)     |
| Barcelona, Catalonia, Spain  | Last updated: `r format(d, "%B, %Y")`  |

: {tbl-colwidths=[70,30]}




## Education

|  |  |
|:-------------------------------------------------|---------------------:|
| PhD in Economics, Universitat Pompeu Fabra | 2028 -- 2032* |
| Master of Research in Economics, Universitat Pompeu Fabra | 2027 -- 2028* |
| Master Program In Economics (PhD Track), Barcelona School of Economics | 2026 -- 2027* |
| Master in Applied Economics, ITAM, High Honors | 2023 -- 2025 |
| BA in Economics, ITAM | 2016 -- 2021 | 



::: {.content-visible when-format="html"}

[\* Expected]{.aside}

:::


::: {.content-visible when-format="typst"}

|  |   |
|---|----:|
|  | \* Expected |

:::


## Working papers

{{< include ../research/working_papers.qmd >}} 

## Selected work in progress

{{< include ../research/work_in_progress.qmd >}}

## Talks & conferences

|  |  |
|:--------------|----------------:|
| ITAM Alumni Conference, Mexico City, Mexico | August 2026** |


::: {.content-visible when-format="html"}

[\** Scheduled]{.aside}

:::


::: {.content-visible when-format="typst"}

|  |   |
|---|----:|
|  | \** Scheduled |

:::



## Professional experience

### Research

|  |  |
|:-------------------------------------------------|---------------------:|
| **World Bank** | **Mexico City, Mexico** |
| **Short Term Consultant** -- Macroeconomics and Growth, Development Research Group. With Agustín Samano | 2025 -- 2026 |

|  |  |
|--------------------------------------------------|---------------------:|
| **ITAM** | **Mexico City, Mexico**  |
| **Research Assistant** -- Center for Economic Research (CIE). With Joyce Sadka and Enrique Seira | 2022 -- 2023 |

### Public service

|                                                 |             |
|-------------------------------------------------|------------:|
| **Instituto Mexicano del Seguro Social (IMSS)** |  **Mexico City, Mexico** |
| **Deputy Head, Fiscal Policy Planning** -- Affiliation and Collection Directorate             | 2023 -- 2025 |

<!-- For translations to Spanish, use:
Deputy Head, Fiscal Policy Planning = Subjefe de División de Planeación de Política Fiscal
Affiliation and Collection Directorate = Dirección de Incorporación y Recaudación -->

### Teaching

{{< include ../teaching/classes.qmd >}}


### Industry 

|                         |      |
|-------------------------|-----:|
| **CEROMULTAS**          | **Mexico City, Mexico**     |
| Senior Business Analyst | 2021 |
| Business Analyst        | 2019 -- 2020 |

|                             |      |
|-----------------------------|-----:|
| **T-Rez Consulting**        | **Mexico City, Mexico**     |
| International Trade Analyst | 2018 | 


## Recognitions

|  |  |
|:---------------|------------------------------------------------------:|
| *Pedro Aspe* Academic excellence award, ITAM | 2026 |
| COFECE Undergraduate Essay Contest (Honorable mention), Mexico | 2021 |

: {tbl-colwidths="\[80,20\]"}

## Languages & technical skills

|                                                    |
|:-----------------------------------------------------|
| **Technical**: Claude Code, R, Python, Stata, SQL, SAS, Quarto, Git, GitHub, Power BI, LaTeX. |
|   **Language**: Spanish (Native), English (Fluent). |

: {tbl-colwidths="\[100\]"}



## Certifications

|  |  |
|:---------------|------------------------------------------------------:|
| [MicroMasters in Data, Economics and Development Policy](https://mitxonline.mit.edu/certificate/program/cc5f08c4-e64b-4f5b-ac83-2fc1868b1c9a/ "Certificate") - MITx | 2023 |

: {tbl-colwidths="\[80,20\]"}